### ISSUE TITLE
Autoreload JS file alone

### ISSUE THREAD

**Issue by zurfyx** [samuelsimoes/chrome-extension-webpack-boilerplate#11]
First of all, your boilerplate looks really good! :+1:

However, in a specific case I am required to load some JavaScript even before the page is rendered. Thus, making `background.html` unsuitable.

```
  "content_scripts": [{
    "js": ["page-load.bundle.js"],
    "matches": ["<all_urls>"],
    "run_at": "document_start",
    "all_frames": true
  }],
```

_According to the [chrome extension documentation](https://developer.chrome.com/extensions/content_scripts#registration) I can use nothing but JS and CSS files_

How would you do it in this case?

Webpack compilation was simply about adding a new entry `"page-load": path.join(__dirname, "src", "js", "page-load.js")` but I don't see how to make the extension get this latest version of the `.js` file without having to reload the extension (or if there are better ways to do this).

**Comment by samuelsimoes** [comment]
If I understood your problem, AFIY there's no way to automatic reload injected scripts except to reload the whole extension. I know, it's a shame. 

Besides that, you must read the [content scripts section in the readme](https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate#content-scripts) before start using content scripts.

**Comment by samuelsimoes** [comment]
Closing. I think it's resolved.

**Comment by howardya** [comment]
@zurfyx please refer to my comment [here](https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/issues/4#issuecomment-326803538) for hot reloading content script.
