### ISSUE TITLE
Move package.json dependencies in devdependencies

### ISSUE THREAD

**Issue by gagarine** [samuelsimoes/chrome-extension-webpack-boilerplate#15]
Most (all?) dependencies are only needed to build and can be moved in devdependencies

**Comment by samuelsimoes** [comment]
For Chrome extensions, I don't find this distinguishment useful. I think `devDependencies` is useful only for libs since it will be part of other packages. IMHO a Chrome extension hardly will be part of another package. 

What do you think?

**Comment by gagarine** [comment]
It's just clearer when you read the package.json: you know witch dependencies are used in your app (like jquery, underscore, ...) and things that are needed has dev/build tools.

So when I read the package I actually don't care about the devdependencies (build tools should just works), but look into dependencies to see what they are using in the app and if their is somethings I don't know I can just have a look to know what it is.

**Comment by gdad-s-river** [comment]
I second @gagarine. It's much cleaner to look at and separate dev ds with ds

**Comment by samuelsimoes** [comment]
Got it. Splitted. 👍
