### ISSUE TITLE
Why use babel?

### ISSUE THREAD

**Issue by gagarine** [samuelsimoes/chrome-extension-webpack-boilerplate#16]
Chrome, Firefox and Edge do support ECMAScript 6: https://kangax.github.io/compat-table/es6/

So why use babel? I'm missing somethings?

**Comment by samuelsimoes** [comment]
Thanks for your observation. You're not missing something, it was my inattention. 😅  
With Webpack 2 we don't even need convert ES6 modules to CommonJS (that is the only thing that browsers don't support yet).

I'll fix this later on. 👍
