### ISSUE TITLE
How to use sass

### ISSUE THREAD

**Issue by gagarine** [samuelsimoes/chrome-extension-webpack-boilerplate#17]
I'm using sass in my plugin. Not sure how I should make it works. (I'm 100% new to webpack)

**Comment by samuelsimoes** [comment]
I don't use Sass, but I believe the `sass-loader` should do the job https://github.com/webpack-contrib/sass-loader#examples

**Comment by samuelsimoes** [comment]
I think that it was resolved, right? So, closing.
