### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by gagarine** [samuelsimoes/chrome-extension-webpack-boilerplate#18]
Most extension are going to have some icons declared in the manifest for icon, and browser action. This should works out of the box no?

**Comment by samuelsimoes** [comment]
It's a possibility. I'll check this later on. 👍

**Comment by gagarine** [comment]
Yeah don't worry for me ;).. I stop using webpack all together for my extension and replace it by simple npm script.

**Comment by grp06** [comment]
@gagarine @samuelsimoes I have the same issue, how can I add an icon to my extension with the current setup? I tried dropping icons into /src and /build and didn't have luck with either

**Comment by gagarine** [comment]
Like I say I use simple npm script now:  https://gist.github.com/gagarine/76d430e73d15c158e1d5d0136b1073ed
