### ISSUE TITLE
Vue dev tools

### ISSUE THREAD

**Issue by gary149** [samuelsimoes/chrome-extension-webpack-boilerplate#2]
Did you find a way to activate the vue dev tools ?
I tried to force ```Vue.config.devtools = true;``` it with but no success so far.

**Comment by samuelsimoes** [comment]
I haven't done anything with Vue.js, so I think that I can't help you.

Maybe your error could be related to the fact that you are running a code from outside (webpack dev server) on the extension's page, like /popup.html and so on.

I'll do some tests later and I'll check this.

**Comment by samuelsimoes** [comment]
Hi @gary149, I made some changes on the boilerplate to run the code from the dist folder (but still using the webpack dev server for hot reload), maybe it could fix your problem. Could you test it for me? Right now I don't know how to setup a vue.js env, so I couldn't test.

**Comment by gary149** [comment]
Ok thanks for your response, I might go back to work on this extension soon if so I'll give a feedback :)

**Comment by samuelsimoes** [comment]
I will consider this resolved. Feel free to open if you have some to add.
