### ISSUE TITLE
Reloading manifest.json file

### ISSUE THREAD

**Issue by mdcanham** [samuelsimoes/chrome-extension-webpack-boilerplate#20]
Can you please confirm that you have to manually restart the extension from chrome://extensions/ when you update the manifest.json file?

**Comment by samuelsimoes** [comment]
As far I know, yes. I don't find any piece of doc confirming it, but by my experiences, I always need to reload the extension.

There is more about this discussion here http://stackoverflow.com/questions/2963260/how-do-i-auto-reload-a-chrome-extension-im-developing

**Comment by mdcanham** [comment]
Great thank you for clearing that up!
