### ISSUE TITLE
How to use background script?

### ISSUE THREAD

**Issue by artemkarpovich** [samuelsimoes/chrome-extension-webpack-boilerplate#22]
In manifest.json I created 

```
"background":
 {
    "scripts": ["background.bundle.js"],
    "persistent": true
  },
```
And in webpack.config.js:

```
entry: {
    popup: path.join(__dirname, "src", "js", "popup.js"),
    content: path.join(__dirname, "src", "js", "content.js"),
    background: path.join(__dirname, "src", "js", "content.js")
  },
  output: {
    path: path.join(__dirname, "build"),
    filename: "[name].bundle.js"
  },
```
After that I started project, background script added to extension, I can open generated background.html, but code in background.js don't execute. thank you

**Comment by samuelsimoes** [comment]
I think there's a typo on your `webpack.config.js`, the background entry point is pointing to `content.js`.

`background: path.join(__dirname, "src", "js", "content.js")`
