### ISSUE TITLE
"webpack-dev-server" https connection error

### ISSUE THREAD

**Issue by mohammadhasanzadeh** [samuelsimoes/chrome-extension-webpack-boilerplate#24]
I get below error on https pages:
`GET https://localhost:3000/sockjs-node/info?t=1504603604813 net::ERR_CONNECTION_CLOSED`

**Comment by samuelsimoes** [comment]
You need active the HTTPS (https://webpack.js.org/configuration/dev-server/#devserver-https) option for webpack dev server at: https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/blob/aea0a585773ae2c655e039da60ae929c001e9ce6/utils/webserver.js#L29-L34

**Comment by samuelsimoes** [comment]
I think it's resolved, right? I'll close, feel free to open with the error persists.
