### ISSUE TITLE
setState can only update a mounted or mounting component warning

### ISSUE THREAD

**Issue by gielcobben** [samuelsimoes/chrome-extension-webpack-boilerplate#25]
Hi, 

I'm trying to use this boilerplate with react (react branch) but when I try to set a state (this.setState) I keep getting this warning in the console:

`warning.js?8a56:33 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactComponent component.`

The component isn't unmounted, even with the easiest state change I get the same warning. Maybe this has something to do with the fact that it's a chrome extension?

I hope someone can help me out here.
Thanks in advance,

Giel.

**Comment by samuelsimoes** [comment]
Can you share some minimal scenario to reproduce this error? I made a quick test here and everything looks fine.

![chrome-extension](https://user-images.githubusercontent.com/1456228/31045839-d531de96-a5c2-11e7-8621-59f2d49fd6b1.gif)

```jsx
export default class extends React.Component {
  constructor () {
    super(...arguments)
    this.state = { name: 'samuel' }
  }

  onClick () {
    this.setState({ name: `other name ${Math.random()}` })
  }

  render () {
    return (
      <div>
        {this.state.name}
        <button type='button' onClick={this.onClick.bind(this)}>
          Change name
        </button>
      </div>
    )
  }
}
```

**Comment by gielcobben** [comment]
Hmm that's weird, I have the same code the only difference is that I put something like: `this.onClick = this.onClick.bind(this);` in the constructor. When you do that you get the error. When I do the binding in the render everything works like expected.

**Comment by samuelsimoes** [comment]
I was investigating this and I found something curious. The problem that you related in fact exists and it is related to the React Hot Reload, I don't know exactly what is happening, but if you include the [es2015 babel preset](https://babeljs.io/docs/plugins/preset-es2015/), everything works fine.

**Comment by occult** [comment]
I also ran into this problem. If you need a quick fix, remove the binding in the constructor and bind it when you call it in the JSX part.

Do this:
`<form className='uk-grid-small' data-uk-grid onSubmit={this.updateResults.bind(this)}>`

**Don't** do this:
`this.updateResults = this.updateResults.bind(this)`

**Comment by ruimcf** [comment]
Just a heads up that using `bind()` on the jsx in the render function might cause some performance degradation, as explained here https://medium.freecodecamp.org/why-arrow-functions-and-bind-in-reacts-render-are-problematic-f1c08b060e36

But yeah, if you just need a fix it is a workaround.

**Comment by samuelsimoes** [comment]
Upgrading the react hot loader to the latest version (f0c9042215d8aa061fa6302d8be09f4ae7f7da76) fixes this problems. 👍
