### ISSUE TITLE
webpack config broken

### ISSUE THREAD

**Issue by sitrobotsit** [samuelsimoes/chrome-extension-webpack-boilerplate#28]
Hi, this line "...JSON.parse(content.toString())" in webpack.config that was recently added, breaks the build.

**Comment by muaaz-vf** [comment]
+1

**Comment by jacksaunders** [comment]
Try using a newer version of node

**Comment by rvasilev** [comment]
@sitrobotsit, the latest LTS release of node is 8.9 and it supports stated syntax without any error.

**Comment by teles** [comment]
+1
