### ISSUE TITLE
webpack config error

### ISSUE THREAD

**Issue by hafizali05** [samuelsimoes/chrome-extension-webpack-boilerplate#42]
The below piece of code with is in webpack.config.js gives me the error shown at the end
```
    new CopyWebpackPlugin([{
      from: "src/manifest.json",
      transform: function (content, path) {
        // generates the manifest file using the package.json informations
        return Buffer.from(JSON.stringify({
          description: process.env.npm_package_description,
          version: process.env.npm_package_version,
          ...JSON.parse(content.toString())
        }))
      }
    }]),
```
Not sure if i am missing some fundamental here but the spread operator doesnt have any property name in the last lines of the code, that is:
          ...JSON.parse(content.toString())

when i do npm start, the error shown in the image is what i get.

> 
> > chrome-extension-webpack@0.0.1 start /Users/practice/WebstormProjects/chrome-extension-webpack-boilerplate
> > node utils/webserver.js
> 
> /Users/practice/WebstormProjects/chrome-extension-webpack-boilerplate/webpack.config.js:67
>           ...JSON.parse(content.toString())
>           ^^^
> 
> SyntaxError: Unexpected token ...
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/Users/practice/WebstormProjects/chrome-extension-webpack-boilerplate/utils/webserver.js:3:14)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! chrome-extension-webpack@0.0.1 start: `node utils/webserver.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the chrome-extension-webpack@0.0.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>

**Comment by hafizali05** [comment]
doesnt work with node version 6.x.x

**Comment by mikicho** [comment]
confim 8.9.4
