### ISSUE TITLE
How to use multiple content scripts?

### ISSUE THREAD

**Issue by AdityaAnand1** [samuelsimoes/chrome-extension-webpack-boilerplate#44]
How do I tell it to bundle all my different content scripts into `myContentScript.bundle.js`?

```
"content_scripts": [
    {
      "matches": ["https://www.google.com/*"],
      "js": ["myContentScript.bundle.js"]
    }
  ]
```

i.e, put multiple scripts into this entry point in webback config

```
  entry: {
    myContentScript: "./src/js/myContentScript.js"
  }
```

**Comment by samuelsimoes** [comment]
Require all your content scripts in `/src/js/myContentScript.js` doesn't do want you want?

**Comment by samuelsimoes** [comment]
Closing by the lack of activity.
