### ISSUE TITLE
Extension Reload?

### ISSUE THREAD

**Issue by okbrown** [samuelsimoes/chrome-extension-webpack-boilerplate#47]
Hi isnt the point of hot module reload to not just re complile on changes but to also reload the extension, without the need to reload it on the extension page?

How do I get this working, or do I need to install something like browser-sync?

**Comment by rvasilev** [comment]
Duplicatw for #41

**Comment by samuelsimoes** [comment]
Like @rvasilev pointed, duplicated. So, closing.
