### ISSUE TITLE
How to access the chrome object?

### ISSUE THREAD

**Issue by EdmundMai** [samuelsimoes/chrome-extension-webpack-boilerplate#48]
How would I access the chrome object and run functions like this?

```
chrome.browserAction.onClicked.addListener(function(tab) {
  chrome.tabs.executeScript({
    code: 'document.body.style.backgroundColor="red"'
  });
});
```

**Comment by samuelsimoes** [comment]
You have two way to do this.

You could use [externals from webpack](https://webpack.js.org/configuration/externals/) or simple prepped `window.` to access the chrome object from outside of the module, like this `window.chrome`.
