### ISSUE TITLE
how can i set static file, like image?

### ISSUE THREAD

**Issue by axetroy** [samuelsimoes/chrome-extension-webpack-boilerplate#5]

**Comment by samuelsimoes** [comment]
@axetroy you can use the https://github.com/webpack/file-loader plugin. For example, on your webpack config file:

```
…
  module: {
    loaders: [
      …
      { test: /\.png$/, loader: "file-loader?name=[name].[ext]" }
    ]
  },
…
```

and your background.js or other entry point:

```
import './my_image.png'
```

**Comment by samuelsimoes** [comment]
I believe the question was answered, so, closing.
