### ISSUE TITLE
For Firefox and Edge also?

### ISSUE THREAD

**Issue by howardya** [samuelsimoes/chrome-extension-webpack-boilerplate#6]
Hi, firstly thank you for sharing this wonderful boilerplate.

I would just like to ask, whether it can be readily converted to be used in firefox and edge?

**Comment by samuelsimoes** [comment]
Thanks!

So, there are no much Chrome specific things in this boilerplate, maybe the most Chrome wise thing could be the https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/blob/master/utils/generate_manifest.js file that generates the Chrome manifest.

I didn't have done anything for Edge and Firefox, so I don't know what kind of adaptations you going need to do, but if these browsers use HTML/Javascript/CSS to build extensions I believe that going to be easy do it.

**Comment by lricoy** [comment]
Hey. Great project!

There are not at lot of differences since they have all agreed to use the WebExtensions standard now. There are some polyfills that need to be loaded for edge since the support for extensions is still on active development. Firefox has some gotchas but the project should be able to support them easily :)

**Comment by samuelsimoes** [comment]
Let's keep this repo focused on the Chrome extensions. Feel free to fork the repo and do the adaptations needed.

**Comment by aguynamedben** [comment]
We pretty easily adopted this for Firefox and Edge.

FYI when you submit to Microsoft you will get a rejection about [unsafe-eval being present](https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/blob/master/src/manifest.json#L15) in manifest.json.

<img width="627" alt="2021-08-24_15-16-46" src="https://user-images.githubusercontent.com/107841/130697340-728b8626-4e4f-4572-a160-534e50eeea83.png">
