### ISSUE TITLE
Resaving source files (with hot reload enabled) causes loss of manifest file

### ISSUE THREAD

**Issue by ArthurG** [samuelsimoes/chrome-extension-webpack-boilerplate#71]
Repro steps:
- `yarn run start`
- Look inside build dir to verify manifest.json is present
- Load extension in chrome
- Change a JS source file
- Look inside build dir to verify manifest.json is NOT present

**Comment by ArthurG** [comment]
Issue seems related to not having a version in the manifest.json file

**Comment by G0L0L** [comment]
> Repro steps:
> 
> * `yarn run start`
> * Look inside build dir to verify manifest.json is present
> * Load extension in chrome
> * Change a JS source file
> * Look inside build dir to verify manifest.json is NOT present

The same scenario works for me. Moreover, it removes everything, which hasn't been built (e.g. was copied by WebpackCopyPlugin). Going to investigate.

**Comment by insub** [comment]
same issue, I figured out the option:
new CopyWebpackPlugin([
      'src/manifest.json',
    ], { copyUnmodified: true })

**Comment by ksoda** [comment]
relates to webpack-contrib/copy-webpack-plugin#261

**Comment by zenzjtech** [comment]
[Another solution here. I've encounter the same issue](https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/issues/85#issuecomment-688274338)

**Comment by albertinator** [comment]
@ArthurG I encountered the same issue and just recently merged a fix. If this continues please open another issue. Thank you!
