### ISSUE TITLE
Webpack 2 issues

### ISSUE THREAD

**Issue by jamez14** [samuelsimoes/chrome-extension-webpack-boilerplate#9]
I wanted to report these but have not had time to investigate reasons/fixes.

1.  Webpack 2 throws an error when attempting to use the `chromeExtensionBoilerplate -> notHotReload` option. I upgrade to webpack 2.3.0 to see if that fixed it but instead I received a more helpful error stating that `chromeExtensionBoilerplate` is not a valid config option, therefore the build/server process comes to a halt in `utils/webserver.js`. As I mentioned, I haven't looked into this at all on the webpack side of things. What I did in the meantime was to just define my content script file names in the `utils/webserver.js` file directly.

2.  Another issue I noticed was that babel was transpiling all of the node_modules and therefore upon start up it would take a very long time (30-60 seconds) to start the dev server. My fix for this was to add the `exclude` property to the babel loader in the webpack config.
`{ test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ },`

If you'd like, I could option a PR for that fix.

Thanks for your work on this repo 👍

**Comment by samuelsimoes** [comment]
I don't know how to fix the first issue. I could remove the `chromeExtensionBoilerplate` from the Webpack options at the webserver start script (`utils/webserver.js`), but when we run `/node_modules/webpack`, the problem will happen again.

The second issue, fixed. 👍

**Comment by samuelsimoes** [comment]
Well, I made a little hacky solution at https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate/commit/1529c39dba1bc68d1cc70a45cba49b20687aaf61 to fix the error with `chromeExtensionBoilerplate`. The build and the web dev server's start with the commands at the `package.json` will work fine.

Thanks for your report.
